CREATE TABLE IF NOT EXISTS "Tasks"(
   id SERIAL PRIMARY KEY,
   description VARCHAR(128) NOT NULL,
   completed BOOLEAN NOT NULL DEFAULT false,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);