FROM golang:alpine
RUN apk add --update --no-cache build-base git ca-certificates

ENV GO111MODULE=on

RUN mkdir /app
ADD . /app
WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

RUN go get github.com/cespare/reflex github.com/go-delve/delve/cmd/dlv

CMD ["chmod", "+x", "./run.sh"]
ENTRYPOINT ["reflex", "-d", "none", "-c", "reflex.conf"]

EXPOSE 40000